# Generated by Django 5.2 on 2025-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedreceipt',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extractedreceipt',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedreceipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
