# Generated by Django 5.2 on 2025-05-11 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_pdf', '0002_alter_extractedreceipt_merchant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedreceipt',
            name='uploaded_file',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='scan_pdf.uploadedfile'),
            preserve_default=False,
        ),
    ]
